# Change these first
owner: RyuXyro # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
#  - name: KazuoYuuka Website
#    url: https://kazuoyuuka.rf.gd
#  - name: RyuXyro Website
#    url: http://ryuxyro.epizy.com
#  - name: Acela
#    url: https://acela.rf.gd
#  - name: RyuXyro Cloud
#    url: https://cloud.ryuxyro.workers.dev/
#  - name: Special 1
#    url: https://special-for-you.rf.gd
#  - name: Special 2
#    url: https://flower.risky.rf.gd/
#  - name: Special 3
#    url: https://need-you.risky.rf.gd/
#  - name: My Galery
#    url: https://one-galery.epizy.com/
#  - name: Moe Count
#    url: https://moe-count.glitch.me
  - name: Risky
    url: https://ryuxyro.my.id/
  - name: Instagram Downloader
    url: https://ryuxyro.github.io/igdownloader/
  - name: safefileku
    url: https://download.safefileku.com/file/aRgzuragzItxb9h4/image1.jpeg/download?hash=cygK8SbTH3vZxDIcJR_Vzw&expire=1749506860&v=2
  - name: Status
    url: https://ryuxyro.github.io/status/


    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: https://RyuXyro.github.io/status
  baseUrl: /status
  theme: dark
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RyuXyro Site Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a **real-time** to see site status
  navbar:
    - title: Github
      href: https://github.com/RyuXyro
    - title: Get Free
      href: https://github.com/RyuXyro/status
    - title: Personal Website
      href: https://ryuxyro.epizy.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
